export const ROUTE_PATH = {
  LOGIN: "/login",
  REGISTER: "/register",
  VERIFY: "/verify",
  HOME: "/",
  PROFILE: "/profile/:id",
  PRODUCT_DETAIL: "/product/:id",
  PRODUCT: "/product",
  SERVICE: "/service",
  SERVICE_DETAIL_PUBLIC: "/service/:id",
  SHOP: "/shop",
  SHOP_PROFILE: "/shop/profile",
  SHOP_EDIT_PROFILE: "/shop/update-profile",
  ORDER: "/order/:id",
  ORDER_SUCCESS: "/order/order-success/:id",
  ORDER_PERSONAL: "/order-personal",
  ORDER_SHOP: "/shop/order-shop",
  PRODUCT_SHOP_MANAGER: "/shop/product-manager",
  SERVICE_SHOP_MANAGER: "/shop/service-manager",
  SERVICE_DETAIL: "/shop/service-manager/:id",
  PRODUCT_MANAGE_DETAIL: "/shop/product-manager/detail/:id",
  CREATE_SERVICE: "/shop/create-service",
  CREATE_PRODUCT: "/shop/create-product",
  BOOKING_SERVICE: "/booking-service/:id",
  BOOKING_SERVICE_SUCCESS: "/booking-service-success/:id",
  BOOKING_PERSONAL: "/booking-personal",
  BOOKING_SHOP: "/shop/booking-shop",
};
